name: Generate and Publish Documentation

on:
  pull_request:
    branches: [ main ]
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.300"
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean
          binaries: OAT/bin/Debug/netstandard2.1/OAT.dll
          output-path: docs/api
          user-email: john.doe@gmail.com
          user-name: John Doe
          project-details-json: project-details.json

